### ISSUE TITLE
Add Kendra's lecture link to resource list

### ISSUE THREAD

**Issue by jbpoline** [QLS600/Intro2Git#1]
Great to see this started ! as a an exercise for someone (ideally, someone who has never done this) you could add the [link to Kendra's lecture](https://www.youtube.com/watch?v=b0ETTTKfu2Y) in the list of resources

**Comment by bzrudski** [comment]
Do you think we should add this to README.md, a new markdown file or a wiki page with resources?

**Comment by kiristern** [comment]
I jotted some useful Git/GH resources on our [teams discussion](https://github.com/orgs/QLS600/teams/classw2022), is that where @jbpoline is referring to? But adding a Resources heading in the ```README``` could also work

**Comment by bzrudski** [comment]
Thanks @kiristern! I found it.

**Comment by jbpoline** [comment]
Great - try to do a pull request for the exercise !

**Comment by bzrudski** [comment]
Thanks @aosakwe for adding the link to the resources. I also added the link to the video in `README.md`. Closing the issue.
